version: '3.8'
services:
  jenkins:
    build:
      context: ./
    privileged: true
      # restart: unless_stopped
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
      - /root:/var/jenkins_home/workspace/
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.ssh/:/root/.ssh/
